### ISSUE TITLE
readme.md

### ISSUE THREAD

**Issue by redlab** [i-Cell-Mobilsoft-Open-Source/swagger-jaxb#5]
Incorrect statement in readme.
The original project is not abandoned  ;-) you can may send PR's.

**Comment by rombow** [comment]
Ok, it was seemed there is no commit soo long time on your project.
I created PR (https://github.com/redlab/swagger-jaxb/pull/15) to resolve changes in our fork and come close some funcions.
We have maven repository release for child project dependency, so this is maximum for now what we can do

**Comment by redlab** [comment]
I did indeed not commit for a long time since I am no longer actively using it myself. But I'm still alive and open to contributions. Where for thanks!

**Comment by rombow** [comment]
Thank you
